export const villas = [
  {
    id: 1,
    name: "Jaipur",
    location: "Rajasthan",
    category: "Desert",
    guests: 11,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "400",
    rating: 4.7,
    image: "/villa1.jpg",
    dailyRent: "4500",
  },
  {
    id: 2,
    name: "Udaipur",
    location: "Rajasthan",
    category: "Lakeside",
    guests: 8,
    bedrooms: 2,
    bathrooms: 3,
    squareMeter: "450",
    rating: 4.4,
    image: "/villa2.jpg",
    dailyRent: "4700",
  },
  {
    id: 3,
    name: "Mumbai",
    location: "Maharashtra",
    category: "Seaside",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa3.jpg",
    dailyRent: "4999",
  },
  {
    id: 4,
    name: "Shimla",
    location: "Himachal Pradesh",
    category: "Mountains",
    guests: 12,
    bedrooms: 10,
    bathrooms: 10,
    squareMeter: "750",
    rating: 5.0,
    image: "/villa4.jpg",
    dailyRent: "8499",
  },
  {
    id: 5,
    name: "Manali",
    location: "Himachal Pradesh",
    category: "Mountains",
    guests: 4,
    bedrooms: 5,
    bathrooms: 6,
    squareMeter: "275",
    rating: 4.0,
    image: "/villa5.jpg",
    dailyRent: "3550",
  },
  {
    id: 6,
    name: "Goa",
    location: "Goa",
    category: "Seaside",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa6.jpg",
    dailyRent: "6950",
  },
  {
    id: 7,
    name: "Ooty",
    location: "Tamil Nadu",
    category: "Hills",
    guests: 15,
    bedrooms: 8,
    bathrooms: 10,
    squareMeter: "1000",
    rating: 4.8,
    image: "/villa7.jpg",
    dailyRent: "7550",
  },
  {
    id: 8,
    name: "Kochi",
    location: "Kerala",
    category: "Seaside",
    guests: 25,
    bedrooms: 25,
    bathrooms: 25,
    squareMeter: "1500",
    rating: 5.0,
    image: "/villa8.jpg",
    dailyRent: "12000",
  },
  {
    id: 9,
    name: "Varanasi",
    location: "Uttar Pradesh",
    category: "Riverside",
    guests: 5,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "240",
    rating: 3.8,
    image: "/villa9.jpg",
    dailyRent: "2500",
  },
];
